/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Alerting EventTypes enum
    /// </summary>
    /// <value>Alerting EventTypes enum</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum AlertingEventTypes
    {
        /// <summary>
        /// Enum NewCrashGroupCreated for value: newCrashGroupCreated
        /// </summary>
        [EnumMember(Value = "newCrashGroupCreated")]
        NewCrashGroupCreated = 1,
        /// <summary>
        /// Enum NewAppReleased for value: newAppReleased
        /// </summary>
        [EnumMember(Value = "newAppReleased")]
        NewAppReleased = 2    }
}
