/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AppMembershipsValidationResponseExcessAppMemberships
    /// </summary>
    [DataContract]
        public partial class AppMembershipsValidationResponseExcessAppMemberships :  IEquatable<AppMembershipsValidationResponseExcessAppMemberships>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppMembershipsValidationResponseExcessAppMemberships" /> class.
        /// </summary>
        /// <param name="appUsersMemberships">appUsersMemberships.</param>
        /// <param name="distributionGroupMemberships">distributionGroupMemberships.</param>
        /// <param name="organizationAdminMemberships">organizationAdminMemberships.</param>
        public AppMembershipsValidationResponseExcessAppMemberships(List<AppMembershipsResponseMemberships> appUsersMemberships = default(List<AppMembershipsResponseMemberships>), List<AppMembershipsResponseMemberships> distributionGroupMemberships = default(List<AppMembershipsResponseMemberships>), List<AppMembershipsResponseMemberships> organizationAdminMemberships = default(List<AppMembershipsResponseMemberships>))
        {
            this.AppUsersMemberships = appUsersMemberships;
            this.DistributionGroupMemberships = distributionGroupMemberships;
            this.OrganizationAdminMemberships = organizationAdminMemberships;
        }
        
        /// <summary>
        /// Gets or Sets AppUsersMemberships
        /// </summary>
        [DataMember(Name="app_users_memberships", EmitDefaultValue=false)]
        public List<AppMembershipsResponseMemberships> AppUsersMemberships { get; set; }

        /// <summary>
        /// Gets or Sets DistributionGroupMemberships
        /// </summary>
        [DataMember(Name="distribution_group_memberships", EmitDefaultValue=false)]
        public List<AppMembershipsResponseMemberships> DistributionGroupMemberships { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationAdminMemberships
        /// </summary>
        [DataMember(Name="organization_admin_memberships", EmitDefaultValue=false)]
        public List<AppMembershipsResponseMemberships> OrganizationAdminMemberships { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AppMembershipsValidationResponseExcessAppMemberships {\n");
            sb.Append("  AppUsersMemberships: ").Append(AppUsersMemberships).Append("\n");
            sb.Append("  DistributionGroupMemberships: ").Append(DistributionGroupMemberships).Append("\n");
            sb.Append("  OrganizationAdminMemberships: ").Append(OrganizationAdminMemberships).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AppMembershipsValidationResponseExcessAppMemberships);
        }

        /// <summary>
        /// Returns true if AppMembershipsValidationResponseExcessAppMemberships instances are equal
        /// </summary>
        /// <param name="input">Instance of AppMembershipsValidationResponseExcessAppMemberships to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AppMembershipsValidationResponseExcessAppMemberships input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AppUsersMemberships == input.AppUsersMemberships ||
                    this.AppUsersMemberships != null &&
                    input.AppUsersMemberships != null &&
                    this.AppUsersMemberships.SequenceEqual(input.AppUsersMemberships)
                ) && 
                (
                    this.DistributionGroupMemberships == input.DistributionGroupMemberships ||
                    this.DistributionGroupMemberships != null &&
                    input.DistributionGroupMemberships != null &&
                    this.DistributionGroupMemberships.SequenceEqual(input.DistributionGroupMemberships)
                ) && 
                (
                    this.OrganizationAdminMemberships == input.OrganizationAdminMemberships ||
                    this.OrganizationAdminMemberships != null &&
                    input.OrganizationAdminMemberships != null &&
                    this.OrganizationAdminMemberships.SequenceEqual(input.OrganizationAdminMemberships)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AppUsersMemberships != null)
                    hashCode = hashCode * 59 + this.AppUsersMemberships.GetHashCode();
                if (this.DistributionGroupMemberships != null)
                    hashCode = hashCode * 59 + this.DistributionGroupMemberships.GetHashCode();
                if (this.OrganizationAdminMemberships != null)
                    hashCode = hashCode * 59 + this.OrganizationAdminMemberships.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
