/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The build configuration in Azure pipeline YAML format
    /// </summary>
    [DataContract]
        public partial class BranchYamlConfiguration :  IEquatable<BranchYamlConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BranchYamlConfiguration" /> class.
        /// </summary>
        /// <param name="yaml">Azure Pipelines YAML file.</param>
        public BranchYamlConfiguration(string yaml = default(string))
        {
            this.Yaml = yaml;
        }
        
        /// <summary>
        /// Azure Pipelines YAML file
        /// </summary>
        /// <value>Azure Pipelines YAML file</value>
        [DataMember(Name="yaml", EmitDefaultValue=false)]
        public string Yaml { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BranchYamlConfiguration {\n");
            sb.Append("  Yaml: ").Append(Yaml).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BranchYamlConfiguration);
        }

        /// <summary>
        /// Returns true if BranchYamlConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of BranchYamlConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BranchYamlConfiguration input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Yaml == input.Yaml ||
                    (this.Yaml != null &&
                    this.Yaml.Equals(input.Yaml))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Yaml != null)
                    hashCode = hashCode * 59 + this.Yaml.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
