/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DistributionGroupsUserVerifyRequest
    /// </summary>
    [DataContract]
        public partial class DistributionGroupsUserVerifyRequest :  IEquatable<DistributionGroupsUserVerifyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DistributionGroupsUserVerifyRequest" /> class.
        /// </summary>
        /// <param name="distributionGroupIds">An array of distribution group ids (required).</param>
        public DistributionGroupsUserVerifyRequest(List<Guid?> distributionGroupIds = default(List<Guid?>))
        {
            // to ensure "distributionGroupIds" is required (not null)
            if (distributionGroupIds == null)
            {
                throw new InvalidDataException("distributionGroupIds is a required property for DistributionGroupsUserVerifyRequest and cannot be null");
            }
            else
            {
                this.DistributionGroupIds = distributionGroupIds;
            }
        }
        
        /// <summary>
        /// An array of distribution group ids
        /// </summary>
        /// <value>An array of distribution group ids</value>
        [DataMember(Name="distribution_group_ids", EmitDefaultValue=false)]
        public List<Guid?> DistributionGroupIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DistributionGroupsUserVerifyRequest {\n");
            sb.Append("  DistributionGroupIds: ").Append(DistributionGroupIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DistributionGroupsUserVerifyRequest);
        }

        /// <summary>
        /// Returns true if DistributionGroupsUserVerifyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DistributionGroupsUserVerifyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DistributionGroupsUserVerifyRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DistributionGroupIds == input.DistributionGroupIds ||
                    this.DistributionGroupIds != null &&
                    input.DistributionGroupIds != null &&
                    this.DistributionGroupIds.SequenceEqual(input.DistributionGroupIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DistributionGroupIds != null)
                    hashCode = hashCode * 59 + this.DistributionGroupIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
