/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GrantAdminRoleRequest
    /// </summary>
    [DataContract]
        public partial class GrantAdminRoleRequest :  IEquatable<GrantAdminRoleRequest>, IValidatableObject
    {
        /// <summary>
        /// The new admin_role
        /// </summary>
        /// <value>The new admin_role</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum AdminRoleEnum
        {
            /// <summary>
            /// Enum SuperAdmin for value: superAdmin
            /// </summary>
            [EnumMember(Value = "superAdmin")]
            SuperAdmin = 1,
            /// <summary>
            /// Enum Admin for value: admin
            /// </summary>
            [EnumMember(Value = "admin")]
            Admin = 2,
            /// <summary>
            /// Enum DevOps for value: devOps
            /// </summary>
            [EnumMember(Value = "devOps")]
            DevOps = 3,
            /// <summary>
            /// Enum CustomerSupport for value: customerSupport
            /// </summary>
            [EnumMember(Value = "customerSupport")]
            CustomerSupport = 4,
            /// <summary>
            /// Enum NotAdmin for value: notAdmin
            /// </summary>
            [EnumMember(Value = "notAdmin")]
            NotAdmin = 5        }
        /// <summary>
        /// The new admin_role
        /// </summary>
        /// <value>The new admin_role</value>
        [DataMember(Name="admin_role", EmitDefaultValue=false)]
        public AdminRoleEnum AdminRole { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GrantAdminRoleRequest" /> class.
        /// </summary>
        /// <param name="adminRole">The new admin_role (required).</param>
        public GrantAdminRoleRequest(AdminRoleEnum adminRole = default(AdminRoleEnum))
        {
            // to ensure "adminRole" is required (not null)
            if (adminRole == null)
            {
                throw new InvalidDataException("adminRole is a required property for GrantAdminRoleRequest and cannot be null");
            }
            else
            {
                this.AdminRole = adminRole;
            }
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GrantAdminRoleRequest {\n");
            sb.Append("  AdminRole: ").Append(AdminRole).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GrantAdminRoleRequest);
        }

        /// <summary>
        /// Returns true if GrantAdminRoleRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GrantAdminRoleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GrantAdminRoleRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AdminRole == input.AdminRole ||
                    (this.AdminRole != null &&
                    this.AdminRole.Equals(input.AdminRole))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AdminRole != null)
                    hashCode = hashCode * 59 + this.AdminRole.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
