/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse20045
    /// </summary>
    [DataContract]
        public partial class InlineResponse20045 :  IEquatable<InlineResponse20045>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20045" /> class.
        /// </summary>
        /// <param name="errorCount">errorCount.</param>
        /// <param name="operatingSystems">operatingSystems.</param>
        public InlineResponse20045(long? errorCount = default(long?), List<ErrorGroupOperatingSystemsOperatingSystems> operatingSystems = default(List<ErrorGroupOperatingSystemsOperatingSystems>))
        {
            this.ErrorCount = errorCount;
            this.OperatingSystems = operatingSystems;
        }
        
        /// <summary>
        /// Gets or Sets ErrorCount
        /// </summary>
        [DataMember(Name="errorCount", EmitDefaultValue=false)]
        public long? ErrorCount { get; set; }

        /// <summary>
        /// Gets or Sets OperatingSystems
        /// </summary>
        [DataMember(Name="operatingSystems", EmitDefaultValue=false)]
        public List<ErrorGroupOperatingSystemsOperatingSystems> OperatingSystems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20045 {\n");
            sb.Append("  ErrorCount: ").Append(ErrorCount).Append("\n");
            sb.Append("  OperatingSystems: ").Append(OperatingSystems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20045);
        }

        /// <summary>
        /// Returns true if InlineResponse20045 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20045 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20045 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ErrorCount == input.ErrorCount ||
                    (this.ErrorCount != null &&
                    this.ErrorCount.Equals(input.ErrorCount))
                ) && 
                (
                    this.OperatingSystems == input.OperatingSystems ||
                    this.OperatingSystems != null &&
                    input.OperatingSystems != null &&
                    this.OperatingSystems.SequenceEqual(input.OperatingSystems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ErrorCount != null)
                    hashCode = hashCode * 59 + this.ErrorCount.GetHashCode();
                if (this.OperatingSystems != null)
                    hashCode = hashCode * 59 + this.OperatingSystems.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
