/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse20088
    /// </summary>
    [DataContract]
        public partial class InlineResponse20088 :  IEquatable<InlineResponse20088>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20088" /> class.
        /// </summary>
        /// <param name="avgCountPerSession">avgCountPerSession.</param>
        /// <param name="previousAvgCountPerSession">previousAvgCountPerSession.</param>
        /// <param name="countPerSession">countPerSession.</param>
        public InlineResponse20088(double? avgCountPerSession = default(double?), double? previousAvgCountPerSession = default(double?), List<EventCountPerDeviceCountPerDevice> countPerSession = default(List<EventCountPerDeviceCountPerDevice>))
        {
            this.AvgCountPerSession = avgCountPerSession;
            this.PreviousAvgCountPerSession = previousAvgCountPerSession;
            this.CountPerSession = countPerSession;
        }
        
        /// <summary>
        /// Gets or Sets AvgCountPerSession
        /// </summary>
        [DataMember(Name="avg_count_per_session", EmitDefaultValue=false)]
        public double? AvgCountPerSession { get; set; }

        /// <summary>
        /// Gets or Sets PreviousAvgCountPerSession
        /// </summary>
        [DataMember(Name="previous_avg_count_per_session", EmitDefaultValue=false)]
        public double? PreviousAvgCountPerSession { get; set; }

        /// <summary>
        /// Gets or Sets CountPerSession
        /// </summary>
        [DataMember(Name="count_per_session", EmitDefaultValue=false)]
        public List<EventCountPerDeviceCountPerDevice> CountPerSession { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20088 {\n");
            sb.Append("  AvgCountPerSession: ").Append(AvgCountPerSession).Append("\n");
            sb.Append("  PreviousAvgCountPerSession: ").Append(PreviousAvgCountPerSession).Append("\n");
            sb.Append("  CountPerSession: ").Append(CountPerSession).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20088);
        }

        /// <summary>
        /// Returns true if InlineResponse20088 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20088 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20088 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AvgCountPerSession == input.AvgCountPerSession ||
                    (this.AvgCountPerSession != null &&
                    this.AvgCountPerSession.Equals(input.AvgCountPerSession))
                ) && 
                (
                    this.PreviousAvgCountPerSession == input.PreviousAvgCountPerSession ||
                    (this.PreviousAvgCountPerSession != null &&
                    this.PreviousAvgCountPerSession.Equals(input.PreviousAvgCountPerSession))
                ) && 
                (
                    this.CountPerSession == input.CountPerSession ||
                    this.CountPerSession != null &&
                    input.CountPerSession != null &&
                    this.CountPerSession.SequenceEqual(input.CountPerSession)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AvgCountPerSession != null)
                    hashCode = hashCode * 59 + this.AvgCountPerSession.GetHashCode();
                if (this.PreviousAvgCountPerSession != null)
                    hashCode = hashCode * 59 + this.PreviousAvgCountPerSession.GetHashCode();
                if (this.CountPerSession != null)
                    hashCode = hashCode * 59 + this.CountPerSession.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
