/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Response for updating release external url
    /// </summary>
    [DataContract]
        public partial class ReleaseExternalUrlUpdateResponse :  IEquatable<ReleaseExternalUrlUpdateResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseExternalUrlUpdateResponse" /> class.
        /// </summary>
        /// <param name="externalDownloadUrl">externalDownloadUrl.</param>
        public ReleaseExternalUrlUpdateResponse(string externalDownloadUrl = default(string))
        {
            this.ExternalDownloadUrl = externalDownloadUrl;
        }
        
        /// <summary>
        /// Gets or Sets ExternalDownloadUrl
        /// </summary>
        [DataMember(Name="external_download_url", EmitDefaultValue=false)]
        public string ExternalDownloadUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReleaseExternalUrlUpdateResponse {\n");
            sb.Append("  ExternalDownloadUrl: ").Append(ExternalDownloadUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReleaseExternalUrlUpdateResponse);
        }

        /// <summary>
        /// Returns true if ReleaseExternalUrlUpdateResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ReleaseExternalUrlUpdateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReleaseExternalUrlUpdateResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ExternalDownloadUrl == input.ExternalDownloadUrl ||
                    (this.ExternalDownloadUrl != null &&
                    this.ExternalDownloadUrl.Equals(input.ExternalDownloadUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalDownloadUrl != null)
                    hashCode = hashCode * 59 + this.ExternalDownloadUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
