/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TestReportSnapshotFatalErrors
    /// </summary>
    [DataContract]
        public partial class TestReportSnapshotFatalErrors :  IEquatable<TestReportSnapshotFatalErrors>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestReportSnapshotFatalErrors" /> class.
        /// </summary>
        /// <param name="deviceSnapshotId">deviceSnapshotId.</param>
        /// <param name="errorMessage">errorMessage.</param>
        /// <param name="errorTitle">errorTitle.</param>
        public TestReportSnapshotFatalErrors(string deviceSnapshotId = default(string), string errorMessage = default(string), string errorTitle = default(string))
        {
            this.DeviceSnapshotId = deviceSnapshotId;
            this.ErrorMessage = errorMessage;
            this.ErrorTitle = errorTitle;
        }
        
        /// <summary>
        /// Gets or Sets DeviceSnapshotId
        /// </summary>
        [DataMember(Name="device_snapshot_id", EmitDefaultValue=false)]
        public string DeviceSnapshotId { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [DataMember(Name="error_message", EmitDefaultValue=false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Gets or Sets ErrorTitle
        /// </summary>
        [DataMember(Name="error_title", EmitDefaultValue=false)]
        public string ErrorTitle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TestReportSnapshotFatalErrors {\n");
            sb.Append("  DeviceSnapshotId: ").Append(DeviceSnapshotId).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  ErrorTitle: ").Append(ErrorTitle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TestReportSnapshotFatalErrors);
        }

        /// <summary>
        /// Returns true if TestReportSnapshotFatalErrors instances are equal
        /// </summary>
        /// <param name="input">Instance of TestReportSnapshotFatalErrors to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestReportSnapshotFatalErrors input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DeviceSnapshotId == input.DeviceSnapshotId ||
                    (this.DeviceSnapshotId != null &&
                    this.DeviceSnapshotId.Equals(input.DeviceSnapshotId))
                ) && 
                (
                    this.ErrorMessage == input.ErrorMessage ||
                    (this.ErrorMessage != null &&
                    this.ErrorMessage.Equals(input.ErrorMessage))
                ) && 
                (
                    this.ErrorTitle == input.ErrorTitle ||
                    (this.ErrorTitle != null &&
                    this.ErrorTitle.Equals(input.ErrorTitle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeviceSnapshotId != null)
                    hashCode = hashCode * 59 + this.DeviceSnapshotId.GetHashCode();
                if (this.ErrorMessage != null)
                    hashCode = hashCode * 59 + this.ErrorMessage.GetHashCode();
                if (this.ErrorTitle != null)
                    hashCode = hashCode * 59 + this.ErrorTitle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
