/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// enumeration of symbol statuses
    /// </summary>
    /// <value>enumeration of symbol statuses</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum V2SymbolStatusEnum
    {
        /// <summary>
        /// Enum Missing for value: missing
        /// </summary>
        [EnumMember(Value = "missing")]
        Missing = 1,
        /// <summary>
        /// Enum Ignored for value: ignored
        /// </summary>
        [EnumMember(Value = "ignored")]
        Ignored = 2,
        /// <summary>
        /// Enum Available for value: available
        /// </summary>
        [EnumMember(Value = "available")]
        Available = 3    }
}
