/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ActiveCrashingAppDetailsAppsWithCrashes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActiveCrashingAppDetailsAppsWithCrashesTests
    {
        // TODO uncomment below to declare an instance variable for ActiveCrashingAppDetailsAppsWithCrashes
        //private ActiveCrashingAppDetailsAppsWithCrashes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActiveCrashingAppDetailsAppsWithCrashes
            //instance = new ActiveCrashingAppDetailsAppsWithCrashes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActiveCrashingAppDetailsAppsWithCrashes
        /// </summary>
        [Test]
        public void ActiveCrashingAppDetailsAppsWithCrashesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActiveCrashingAppDetailsAppsWithCrashes
            //Assert.IsInstanceOfType<ActiveCrashingAppDetailsAppsWithCrashes> (instance, "variable 'instance' is a ActiveCrashingAppDetailsAppsWithCrashes");
        }


        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Test]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'CrashGroupId'
        /// </summary>
        [Test]
        public void CrashGroupIdTest()
        {
            // TODO unit test for the property 'CrashGroupId'
        }

    }

}
