/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AggregatedBillingInformationBillingPlansBuildService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AggregatedBillingInformationBillingPlansBuildServiceTests
    {
        // TODO uncomment below to declare an instance variable for AggregatedBillingInformationBillingPlansBuildService
        //private AggregatedBillingInformationBillingPlansBuildService instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AggregatedBillingInformationBillingPlansBuildService
            //instance = new AggregatedBillingInformationBillingPlansBuildService();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AggregatedBillingInformationBillingPlansBuildService
        /// </summary>
        [Test]
        public void AggregatedBillingInformationBillingPlansBuildServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AggregatedBillingInformationBillingPlansBuildService
            //Assert.IsInstanceOfType<AggregatedBillingInformationBillingPlansBuildService> (instance, "variable 'instance' is a AggregatedBillingInformationBillingPlansBuildService");
        }


        /// <summary>
        /// Test the property 'CanSelectTrialPlan'
        /// </summary>
        [Test]
        public void CanSelectTrialPlanTest()
        {
            // TODO unit test for the property 'CanSelectTrialPlan'
        }
        /// <summary>
        /// Test the property 'LastTrialPlanExpirationTime'
        /// </summary>
        [Test]
        public void LastTrialPlanExpirationTimeTest()
        {
            // TODO unit test for the property 'LastTrialPlanExpirationTime'
        }
        /// <summary>
        /// Test the property 'CurrentBillingPeriod'
        /// </summary>
        [Test]
        public void CurrentBillingPeriodTest()
        {
            // TODO unit test for the property 'CurrentBillingPeriod'
        }

    }

}
