/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AllOfLegacyUpdateCheckResponseUpdateInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AllOfLegacyUpdateCheckResponseUpdateInfoTests
    {
        // TODO uncomment below to declare an instance variable for AllOfLegacyUpdateCheckResponseUpdateInfo
        //private AllOfLegacyUpdateCheckResponseUpdateInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AllOfLegacyUpdateCheckResponseUpdateInfo
            //instance = new AllOfLegacyUpdateCheckResponseUpdateInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AllOfLegacyUpdateCheckResponseUpdateInfo
        /// </summary>
        [Test]
        public void AllOfLegacyUpdateCheckResponseUpdateInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AllOfLegacyUpdateCheckResponseUpdateInfo
            //Assert.IsInstanceOfType<AllOfLegacyUpdateCheckResponseUpdateInfo> (instance, "variable 'instance' is a AllOfLegacyUpdateCheckResponseUpdateInfo");
        }


        /// <summary>
        /// Test the property 'DownloadURL'
        /// </summary>
        [Test]
        public void DownloadURLTest()
        {
            // TODO unit test for the property 'DownloadURL'
        }
        /// <summary>
        /// Test the property 'IsAvailable'
        /// </summary>
        [Test]
        public void IsAvailableTest()
        {
            // TODO unit test for the property 'IsAvailable'
        }
        /// <summary>
        /// Test the property 'PackageSize'
        /// </summary>
        [Test]
        public void PackageSizeTest()
        {
            // TODO unit test for the property 'PackageSize'
        }
        /// <summary>
        /// Test the property 'ShouldRunBinaryVersion'
        /// </summary>
        [Test]
        public void ShouldRunBinaryVersionTest()
        {
            // TODO unit test for the property 'ShouldRunBinaryVersion'
        }
        /// <summary>
        /// Test the property 'UpdateAppVersion'
        /// </summary>
        [Test]
        public void UpdateAppVersionTest()
        {
            // TODO unit test for the property 'UpdateAppVersion'
        }
        /// <summary>
        /// Test the property 'PackageHash'
        /// </summary>
        [Test]
        public void PackageHashTest()
        {
            // TODO unit test for the property 'PackageHash'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

    }

}
