/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ApiTokensPrivateCreateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiTokensPrivateCreateResponseTests
    {
        // TODO uncomment below to declare an instance variable for ApiTokensPrivateCreateResponse
        //private ApiTokensPrivateCreateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiTokensPrivateCreateResponse
            //instance = new ApiTokensPrivateCreateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiTokensPrivateCreateResponse
        /// </summary>
        [Test]
        public void ApiTokensPrivateCreateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiTokensPrivateCreateResponse
            //Assert.IsInstanceOfType<ApiTokensPrivateCreateResponse> (instance, "variable 'instance' is a ApiTokensPrivateCreateResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'EncryptedToken'
        /// </summary>
        [Test]
        public void EncryptedTokenTest()
        {
            // TODO unit test for the property 'EncryptedToken'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ApiToken'
        /// </summary>
        [Test]
        public void ApiTokenTest()
        {
            // TODO unit test for the property 'ApiToken'
        }

    }

}
