/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppleMappingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppleMappingResponseTests
    {
        // TODO uncomment below to declare an instance variable for AppleMappingResponse
        //private AppleMappingResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppleMappingResponse
            //instance = new AppleMappingResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppleMappingResponse
        /// </summary>
        [Test]
        public void AppleMappingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppleMappingResponse
            //Assert.IsInstanceOfType<AppleMappingResponse> (instance, "variable 'instance' is a AppleMappingResponse");
        }


        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'ServiceConnectionId'
        /// </summary>
        [Test]
        public void ServiceConnectionIdTest()
        {
            // TODO unit test for the property 'ServiceConnectionId'
        }
        /// <summary>
        /// Test the property 'AppleId'
        /// </summary>
        [Test]
        public void AppleIdTest()
        {
            // TODO unit test for the property 'AppleId'
        }
        /// <summary>
        /// Test the property 'TeamIdentifier'
        /// </summary>
        [Test]
        public void TeamIdentifierTest()
        {
            // TODO unit test for the property 'TeamIdentifier'
        }

    }

}
