/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ApplicationStatusRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApplicationStatusRequestTests
    {
        // TODO uncomment below to declare an instance variable for ApplicationStatusRequest
        //private ApplicationStatusRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApplicationStatusRequest
            //instance = new ApplicationStatusRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApplicationStatusRequest
        /// </summary>
        [Test]
        public void ApplicationStatusRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplicationStatusRequest
            //Assert.IsInstanceOfType<ApplicationStatusRequest> (instance, "variable 'instance' is a ApplicationStatusRequest");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'BundleIdentifier'
        /// </summary>
        [Test]
        public void BundleIdentifierTest()
        {
            // TODO unit test for the property 'BundleIdentifier'
        }
        /// <summary>
        /// Test the property 'TrackIdentifier'
        /// </summary>
        [Test]
        public void TrackIdentifierTest()
        {
            // TODO unit test for the property 'TrackIdentifier'
        }
        /// <summary>
        /// Test the property 'BuildVersion'
        /// </summary>
        [Test]
        public void BuildVersionTest()
        {
            // TODO unit test for the property 'BuildVersion'
        }
        /// <summary>
        /// Test the property 'TeamIdentifier'
        /// </summary>
        [Test]
        public void TeamIdentifierTest()
        {
            // TODO unit test for the property 'TeamIdentifier'
        }
        /// <summary>
        /// Test the property 'TrainVersion'
        /// </summary>
        [Test]
        public void TrainVersionTest()
        {
            // TODO unit test for the property 'TrainVersion'
        }

    }

}
