/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppMembershipsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppMembershipsResponseTests
    {
        // TODO uncomment below to declare an instance variable for AppMembershipsResponse
        //private AppMembershipsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppMembershipsResponse
            //instance = new AppMembershipsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppMembershipsResponse
        /// </summary>
        [Test]
        public void AppMembershipsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppMembershipsResponse
            //Assert.IsInstanceOfType<AppMembershipsResponse> (instance, "variable 'instance' is a AppMembershipsResponse");
        }


        /// <summary>
        /// Test the property 'AppOrigin'
        /// </summary>
        [Test]
        public void AppOriginTest()
        {
            // TODO unit test for the property 'AppOrigin'
        }
        /// <summary>
        /// Test the property 'Memberships'
        /// </summary>
        [Test]
        public void MembershipsTest()
        {
            // TODO unit test for the property 'Memberships'
        }

    }

}
