/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppNameExportConfigurationsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppNameExportConfigurationsBodyTests
    {
        // TODO uncomment below to declare an instance variable for AppNameExportConfigurationsBody
        //private AppNameExportConfigurationsBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppNameExportConfigurationsBody
            //instance = new AppNameExportConfigurationsBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppNameExportConfigurationsBody
        /// </summary>
        [Test]
        public void AppNameExportConfigurationsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppNameExportConfigurationsBody
            //Assert.IsInstanceOfType<AppNameExportConfigurationsBody> (instance, "variable 'instance' is a AppNameExportConfigurationsBody");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ExportEntities'
        /// </summary>
        [Test]
        public void ExportEntitiesTest()
        {
            // TODO unit test for the property 'ExportEntities'
        }
        /// <summary>
        /// Test the property 'ResourceName'
        /// </summary>
        [Test]
        public void ResourceNameTest()
        {
            // TODO unit test for the property 'ResourceName'
        }
        /// <summary>
        /// Test the property 'ResourceGroup'
        /// </summary>
        [Test]
        public void ResourceGroupTest()
        {
            // TODO unit test for the property 'ResourceGroup'
        }
        /// <summary>
        /// Test the property 'Backfill'
        /// </summary>
        [Test]
        public void BackfillTest()
        {
            // TODO unit test for the property 'Backfill'
        }

    }

}
