/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BillingInformationSearchResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingInformationSearchResultsTests
    {
        // TODO uncomment below to declare an instance variable for BillingInformationSearchResults
        //private BillingInformationSearchResults instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingInformationSearchResults
            //instance = new BillingInformationSearchResults();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingInformationSearchResults
        /// </summary>
        [Test]
        public void BillingInformationSearchResultsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingInformationSearchResults
            //Assert.IsInstanceOfType<BillingInformationSearchResults> (instance, "variable 'instance' is a BillingInformationSearchResults");
        }



    }

}
