/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BranchConfigurationToolsets
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BranchConfigurationToolsetsTests
    {
        // TODO uncomment below to declare an instance variable for BranchConfigurationToolsets
        //private BranchConfigurationToolsets instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BranchConfigurationToolsets
            //instance = new BranchConfigurationToolsets();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BranchConfigurationToolsets
        /// </summary>
        [Test]
        public void BranchConfigurationToolsetsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BranchConfigurationToolsets
            //Assert.IsInstanceOfType<BranchConfigurationToolsets> (instance, "variable 'instance' is a BranchConfigurationToolsets");
        }


        /// <summary>
        /// Test the property 'Xcode'
        /// </summary>
        [Test]
        public void XcodeTest()
        {
            // TODO unit test for the property 'Xcode'
        }
        /// <summary>
        /// Test the property 'Javascript'
        /// </summary>
        [Test]
        public void JavascriptTest()
        {
            // TODO unit test for the property 'Javascript'
        }
        /// <summary>
        /// Test the property 'Xamarin'
        /// </summary>
        [Test]
        public void XamarinTest()
        {
            // TODO unit test for the property 'Xamarin'
        }
        /// <summary>
        /// Test the property 'Android'
        /// </summary>
        [Test]
        public void AndroidTest()
        {
            // TODO unit test for the property 'Android'
        }

    }

}
