/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BranchConfigurationRevision
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BranchConfigurationRevisionTests
    {
        // TODO uncomment below to declare an instance variable for BranchConfigurationRevision
        //private BranchConfigurationRevision instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BranchConfigurationRevision
            //instance = new BranchConfigurationRevision();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BranchConfigurationRevision
        /// </summary>
        [Test]
        public void BranchConfigurationRevisionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BranchConfigurationRevision
            //Assert.IsInstanceOfType<BranchConfigurationRevision> (instance, "variable 'instance' is a BranchConfigurationRevision");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }
        /// <summary>
        /// Test the property 'ChangedDate'
        /// </summary>
        [Test]
        public void ChangedDateTest()
        {
            // TODO unit test for the property 'ChangedDate'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ChangeType'
        /// </summary>
        [Test]
        public void ChangeTypeTest()
        {
            // TODO unit test for the property 'ChangeType'
        }
        /// <summary>
        /// Test the property 'DefinitionUrl'
        /// </summary>
        [Test]
        public void DefinitionUrlTest()
        {
            // TODO unit test for the property 'DefinitionUrl'
        }
        /// <summary>
        /// Test the property 'ChangedBy'
        /// </summary>
        [Test]
        public void ChangedByTest()
        {
            // TODO unit test for the property 'ChangedBy'
        }

    }

}
