/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BuildConcurrencyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuildConcurrencyResponseTests
    {
        // TODO uncomment below to declare an instance variable for BuildConcurrencyResponse
        //private BuildConcurrencyResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuildConcurrencyResponse
            //instance = new BuildConcurrencyResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuildConcurrencyResponse
        /// </summary>
        [Test]
        public void BuildConcurrencyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuildConcurrencyResponse
            //Assert.IsInstanceOfType<BuildConcurrencyResponse> (instance, "variable 'instance' is a BuildConcurrencyResponse");
        }


        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'CommittedQuantity'
        /// </summary>
        [Test]
        public void CommittedQuantityTest()
        {
            // TODO unit test for the property 'CommittedQuantity'
        }

    }

}
