/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DevicesRegisterBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DevicesRegisterBodyTests
    {
        // TODO uncomment below to declare an instance variable for DevicesRegisterBody
        //private DevicesRegisterBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DevicesRegisterBody
            //instance = new DevicesRegisterBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DevicesRegisterBody
        /// </summary>
        [Test]
        public void DevicesRegisterBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DevicesRegisterBody
            //Assert.IsInstanceOfType<DevicesRegisterBody> (instance, "variable 'instance' is a DevicesRegisterBody");
        }


        /// <summary>
        /// Test the property 'Udid'
        /// </summary>
        [Test]
        public void UdidTest()
        {
            // TODO unit test for the property 'Udid'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'OsBuild'
        /// </summary>
        [Test]
        public void OsBuildTest()
        {
            // TODO unit test for the property 'OsBuild'
        }
        /// <summary>
        /// Test the property 'OsVersion'
        /// </summary>
        [Test]
        public void OsVersionTest()
        {
            // TODO unit test for the property 'OsVersion'
        }
        /// <summary>
        /// Test the property 'Serial'
        /// </summary>
        [Test]
        public void SerialTest()
        {
            // TODO unit test for the property 'Serial'
        }
        /// <summary>
        /// Test the property 'Imei'
        /// </summary>
        [Test]
        public void ImeiTest()
        {
            // TODO unit test for the property 'Imei'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }

    }

}
