/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeviceMemory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceMemoryTests
    {
        // TODO uncomment below to declare an instance variable for DeviceMemory
        //private DeviceMemory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceMemory
            //instance = new DeviceMemory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceMemory
        /// </summary>
        [Test]
        public void DeviceMemoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeviceMemory
            //Assert.IsInstanceOfType<DeviceMemory> (instance, "variable 'instance' is a DeviceMemory");
        }


        /// <summary>
        /// Test the property 'FormattedSize'
        /// </summary>
        [Test]
        public void FormattedSizeTest()
        {
            // TODO unit test for the property 'FormattedSize'
        }

    }

}
