/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeviceSet1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceSet1Tests
    {
        // TODO uncomment below to declare an instance variable for DeviceSet1
        //private DeviceSet1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceSet1
            //instance = new DeviceSet1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceSet1
        /// </summary>
        [Test]
        public void DeviceSet1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeviceSet1
            //Assert.IsInstanceOfType<DeviceSet1> (instance, "variable 'instance' is a DeviceSet1");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ManufacturerCount'
        /// </summary>
        [Test]
        public void ManufacturerCountTest()
        {
            // TODO unit test for the property 'ManufacturerCount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Test]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'OsVersionCount'
        /// </summary>
        [Test]
        public void OsVersionCountTest()
        {
            // TODO unit test for the property 'OsVersionCount'
        }
        /// <summary>
        /// Test the property 'DeviceConfigurations'
        /// </summary>
        [Test]
        public void DeviceConfigurationsTest()
        {
            // TODO unit test for the property 'DeviceConfigurations'
        }

    }

}
