/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ErrorGroupModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorGroupModelTests
    {
        // TODO uncomment below to declare an instance variable for ErrorGroupModel
        //private ErrorGroupModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorGroupModel
            //instance = new ErrorGroupModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorGroupModel
        /// </summary>
        [Test]
        public void ErrorGroupModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorGroupModel
            //Assert.IsInstanceOfType<ErrorGroupModel> (instance, "variable 'instance' is a ErrorGroupModel");
        }


        /// <summary>
        /// Test the property 'ModelName'
        /// </summary>
        [Test]
        public void ModelNameTest()
        {
            // TODO unit test for the property 'ModelName'
        }
        /// <summary>
        /// Test the property 'ModelCode'
        /// </summary>
        [Test]
        public void ModelCodeTest()
        {
            // TODO unit test for the property 'ModelCode'
        }
        /// <summary>
        /// Test the property 'ErrorCount'
        /// </summary>
        [Test]
        public void ErrorCountTest()
        {
            // TODO unit test for the property 'ErrorCount'
        }

    }

}
