/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ErrorGroups
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorGroupsTests
    {
        // TODO uncomment below to declare an instance variable for ErrorGroups
        //private ErrorGroups instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorGroups
            //instance = new ErrorGroups();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorGroups
        /// </summary>
        [Test]
        public void ErrorGroupsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorGroups
            //Assert.IsInstanceOfType<ErrorGroups> (instance, "variable 'instance' is a ErrorGroups");
        }


        /// <summary>
        /// Test the property 'NextLink'
        /// </summary>
        [Test]
        public void NextLinkTest()
        {
            // TODO unit test for the property 'NextLink'
        }
        /// <summary>
        /// Test the property '_ErrorGroups'
        /// </summary>
        [Test]
        public void _ErrorGroupsTest()
        {
            // TODO unit test for the property '_ErrorGroups'
        }

    }

}
