/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EventPropertyValuesValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventPropertyValuesValuesTests
    {
        // TODO uncomment below to declare an instance variable for EventPropertyValuesValues
        //private EventPropertyValuesValues instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventPropertyValuesValues
            //instance = new EventPropertyValuesValues();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventPropertyValuesValues
        /// </summary>
        [Test]
        public void EventPropertyValuesValuesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventPropertyValuesValues
            //Assert.IsInstanceOfType<EventPropertyValuesValues> (instance, "variable 'instance' is a EventPropertyValuesValues");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'PreviousCount'
        /// </summary>
        [Test]
        public void PreviousCountTest()
        {
            // TODO unit test for the property 'PreviousCount'
        }

    }

}
