/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20070
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20070Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20070
        //private InlineResponse20070 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20070
            //instance = new InlineResponse20070();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20070
        /// </summary>
        [Test]
        public void InlineResponse20070InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20070
            //Assert.IsInstanceOfType<InlineResponse20070> (instance, "variable 'instance' is a InlineResponse20070");
        }


        /// <summary>
        /// Test the property 'CrashGroupId'
        /// </summary>
        [Test]
        public void CrashGroupIdTest()
        {
            // TODO unit test for the property 'CrashGroupId'
        }
        /// <summary>
        /// Test the property 'NewCrashGroupId'
        /// </summary>
        [Test]
        public void NewCrashGroupIdTest()
        {
            // TODO unit test for the property 'NewCrashGroupId'
        }
        /// <summary>
        /// Test the property 'DisplayId'
        /// </summary>
        [Test]
        public void DisplayIdTest()
        {
            // TODO unit test for the property 'DisplayId'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Test]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Test]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'ImpactedUsers'
        /// </summary>
        [Test]
        public void ImpactedUsersTest()
        {
            // TODO unit test for the property 'ImpactedUsers'
        }
        /// <summary>
        /// Test the property 'FirstOccurrence'
        /// </summary>
        [Test]
        public void FirstOccurrenceTest()
        {
            // TODO unit test for the property 'FirstOccurrence'
        }
        /// <summary>
        /// Test the property 'LastOccurrence'
        /// </summary>
        [Test]
        public void LastOccurrenceTest()
        {
            // TODO unit test for the property 'LastOccurrence'
        }
        /// <summary>
        /// Test the property 'Exception'
        /// </summary>
        [Test]
        public void ExceptionTest()
        {
            // TODO unit test for the property 'Exception'
        }
        /// <summary>
        /// Test the property 'CrashReason'
        /// </summary>
        [Test]
        public void CrashReasonTest()
        {
            // TODO unit test for the property 'CrashReason'
        }
        /// <summary>
        /// Test the property 'ReasonFrame'
        /// </summary>
        [Test]
        public void ReasonFrameTest()
        {
            // TODO unit test for the property 'ReasonFrame'
        }
        /// <summary>
        /// Test the property 'Fatal'
        /// </summary>
        [Test]
        public void FatalTest()
        {
            // TODO unit test for the property 'Fatal'
        }
        /// <summary>
        /// Test the property 'Annotation'
        /// </summary>
        [Test]
        public void AnnotationTest()
        {
            // TODO unit test for the property 'Annotation'
        }

    }

}
