/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20076
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20076Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20076
        //private InlineResponse20076 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20076
            //instance = new InlineResponse20076();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20076
        /// </summary>
        [Test]
        public void InlineResponse20076InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20076
            //Assert.IsInstanceOfType<InlineResponse20076> (instance, "variable 'instance' is a InlineResponse20076");
        }


        /// <summary>
        /// Test the property 'AverageSessionsPerUser'
        /// </summary>
        [Test]
        public void AverageSessionsPerUserTest()
        {
            // TODO unit test for the property 'AverageSessionsPerUser'
        }
        /// <summary>
        /// Test the property 'PreviousAverageSessionsPerUser'
        /// </summary>
        [Test]
        public void PreviousAverageSessionsPerUserTest()
        {
            // TODO unit test for the property 'PreviousAverageSessionsPerUser'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }
        /// <summary>
        /// Test the property 'PreviousTotalCount'
        /// </summary>
        [Test]
        public void PreviousTotalCountTest()
        {
            // TODO unit test for the property 'PreviousTotalCount'
        }
        /// <summary>
        /// Test the property 'SessionsPerUser'
        /// </summary>
        [Test]
        public void SessionsPerUserTest()
        {
            // TODO unit test for the property 'SessionsPerUser'
        }

    }

}
