/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20097
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20097Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20097
        //private InlineResponse20097 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20097
            //instance = new InlineResponse20097();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20097
        /// </summary>
        [Test]
        public void InlineResponse20097InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20097
            //Assert.IsInstanceOfType<InlineResponse20097> (instance, "variable 'instance' is a InlineResponse20097");
        }


        /// <summary>
        /// Test the property 'Organizations'
        /// </summary>
        [Test]
        public void OrganizationsTest()
        {
            // TODO unit test for the property 'Organizations'
        }

    }

}
