/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20024
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20024Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20024
        //private InlineResponse20024 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20024
            //instance = new InlineResponse20024();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20024
        /// </summary>
        [Test]
        public void InlineResponse20024InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20024
            //Assert.IsInstanceOfType<InlineResponse20024> (instance, "variable 'instance' is a InlineResponse20024");
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'HashFileId'
        /// </summary>
        [Test]
        public void HashFileIdTest()
        {
            // TODO unit test for the property 'HashFileId'
        }
        /// <summary>
        /// Test the property 'AppUploadId'
        /// </summary>
        [Test]
        public void AppUploadIdTest()
        {
            // TODO unit test for the property 'AppUploadId'
        }
        /// <summary>
        /// Test the property 'HashFileUrl'
        /// </summary>
        [Test]
        public void HashFileUrlTest()
        {
            // TODO unit test for the property 'HashFileUrl'
        }

    }

}
