/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InternalBulkAppResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InternalBulkAppResponseTests
    {
        // TODO uncomment below to declare an instance variable for InternalBulkAppResponse
        //private InternalBulkAppResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InternalBulkAppResponse
            //instance = new InternalBulkAppResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InternalBulkAppResponse
        /// </summary>
        [Test]
        public void InternalBulkAppResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InternalBulkAppResponse
            //Assert.IsInstanceOfType<InternalBulkAppResponse> (instance, "variable 'instance' is a InternalBulkAppResponse");
        }


        /// <summary>
        /// Test the property 'AppName'
        /// </summary>
        [Test]
        public void AppNameTest()
        {
            // TODO unit test for the property 'AppName'
        }
        /// <summary>
        /// Test the property 'OwnerDisplayName'
        /// </summary>
        [Test]
        public void OwnerDisplayNameTest()
        {
            // TODO unit test for the property 'OwnerDisplayName'
        }

    }

}
