/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IntuneAppsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IntuneAppsResponseTests
    {
        // TODO uncomment below to declare an instance variable for IntuneAppsResponse
        //private IntuneAppsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IntuneAppsResponse
            //instance = new IntuneAppsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IntuneAppsResponse
        /// </summary>
        [Test]
        public void IntuneAppsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IntuneAppsResponse
            //Assert.IsInstanceOfType<IntuneAppsResponse> (instance, "variable 'instance' is a IntuneAppsResponse");
        }


        /// <summary>
        /// Test the property 'CreatedMonth'
        /// </summary>
        [Test]
        public void CreatedMonthTest()
        {
            // TODO unit test for the property 'CreatedMonth'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'RefreshStatus'
        /// </summary>
        [Test]
        public void RefreshStatusTest()
        {
            // TODO unit test for the property 'RefreshStatus'
        }

    }

}
