/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LegacyAuthenticationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LegacyAuthenticationResponseTests
    {
        // TODO uncomment below to declare an instance variable for LegacyAuthenticationResponse
        //private LegacyAuthenticationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LegacyAuthenticationResponse
            //instance = new LegacyAuthenticationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LegacyAuthenticationResponse
        /// </summary>
        [Test]
        public void LegacyAuthenticationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LegacyAuthenticationResponse
            //Assert.IsInstanceOfType<LegacyAuthenticationResponse> (instance, "variable 'instance' is a LegacyAuthenticationResponse");
        }


        /// <summary>
        /// Test the property 'Authenticated'
        /// </summary>
        [Test]
        public void AuthenticatedTest()
        {
            // TODO unit test for the property 'Authenticated'
        }

    }

}
