/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LegacyDeploymentsResponseDeployments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LegacyDeploymentsResponseDeploymentsTests
    {
        // TODO uncomment below to declare an instance variable for LegacyDeploymentsResponseDeployments
        //private LegacyDeploymentsResponseDeployments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LegacyDeploymentsResponseDeployments
            //instance = new LegacyDeploymentsResponseDeployments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LegacyDeploymentsResponseDeployments
        /// </summary>
        [Test]
        public void LegacyDeploymentsResponseDeploymentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LegacyDeploymentsResponseDeployments
            //Assert.IsInstanceOfType<LegacyDeploymentsResponseDeployments> (instance, "variable 'instance' is a LegacyDeploymentsResponseDeployments");
        }


        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Test]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Package'
        /// </summary>
        [Test]
        public void PackageTest()
        {
            // TODO unit test for the property 'Package'
        }

    }

}
