/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PublishDevicesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublishDevicesRequestTests
    {
        // TODO uncomment below to declare an instance variable for PublishDevicesRequest
        //private PublishDevicesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublishDevicesRequest
            //instance = new PublishDevicesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublishDevicesRequest
        /// </summary>
        [Test]
        public void PublishDevicesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublishDevicesRequest
            //Assert.IsInstanceOfType<PublishDevicesRequest> (instance, "variable 'instance' is a PublishDevicesRequest");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'AccountServiceConnectionId'
        /// </summary>
        [Test]
        public void AccountServiceConnectionIdTest()
        {
            // TODO unit test for the property 'AccountServiceConnectionId'
        }
        /// <summary>
        /// Test the property 'PublishAllDevices'
        /// </summary>
        [Test]
        public void PublishAllDevicesTest()
        {
            // TODO unit test for the property 'PublishAllDevices'
        }
        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Test]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }

    }

}
