/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReleaseCounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReleaseCountsTests
    {
        // TODO uncomment below to declare an instance variable for ReleaseCounts
        //private ReleaseCounts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReleaseCounts
            //instance = new ReleaseCounts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReleaseCounts
        /// </summary>
        [Test]
        public void ReleaseCountsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReleaseCounts
            //Assert.IsInstanceOfType<ReleaseCounts> (instance, "variable 'instance' is a ReleaseCounts");
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Test]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }

    }

}
