/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReleaseCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReleaseCreateRequestTests
    {
        // TODO uncomment below to declare an instance variable for ReleaseCreateRequest
        //private ReleaseCreateRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReleaseCreateRequest
            //instance = new ReleaseCreateRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReleaseCreateRequest
        /// </summary>
        [Test]
        public void ReleaseCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReleaseCreateRequest
            //Assert.IsInstanceOfType<ReleaseCreateRequest> (instance, "variable 'instance' is a ReleaseCreateRequest");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'BuildVersion'
        /// </summary>
        [Test]
        public void BuildVersionTest()
        {
            // TODO unit test for the property 'BuildVersion'
        }
        /// <summary>
        /// Test the property 'UniqueIdentifier'
        /// </summary>
        [Test]
        public void UniqueIdentifierTest()
        {
            // TODO unit test for the property 'UniqueIdentifier'
        }
        /// <summary>
        /// Test the property 'MinimumOsVersion'
        /// </summary>
        [Test]
        public void MinimumOsVersionTest()
        {
            // TODO unit test for the property 'MinimumOsVersion'
        }
        /// <summary>
        /// Test the property 'DeviceFamily'
        /// </summary>
        [Test]
        public void DeviceFamilyTest()
        {
            // TODO unit test for the property 'DeviceFamily'
        }
        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Test]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }
        /// <summary>
        /// Test the property 'Fingerprint'
        /// </summary>
        [Test]
        public void FingerprintTest()
        {
            // TODO unit test for the property 'Fingerprint'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'PackageUrl'
        /// </summary>
        [Test]
        public void PackageUrlTest()
        {
            // TODO unit test for the property 'PackageUrl'
        }
        /// <summary>
        /// Test the property 'FileExtension'
        /// </summary>
        [Test]
        public void FileExtensionTest()
        {
            // TODO unit test for the property 'FileExtension'
        }
        /// <summary>
        /// Test the property 'UploadId'
        /// </summary>
        [Test]
        public void UploadIdTest()
        {
            // TODO unit test for the property 'UploadId'
        }
        /// <summary>
        /// Test the property 'IconAssetId'
        /// </summary>
        [Test]
        public void IconAssetIdTest()
        {
            // TODO unit test for the property 'IconAssetId'
        }
        /// <summary>
        /// Test the property 'IpaUuids'
        /// </summary>
        [Test]
        public void IpaUuidsTest()
        {
            // TODO unit test for the property 'IpaUuids'
        }
        /// <summary>
        /// Test the property 'Provision'
        /// </summary>
        [Test]
        public void ProvisionTest()
        {
            // TODO unit test for the property 'Provision'
        }
        /// <summary>
        /// Test the property 'AppexProvisioningProfiles'
        /// </summary>
        [Test]
        public void AppexProvisioningProfilesTest()
        {
            // TODO unit test for the property 'AppexProvisioningProfiles'
        }
        /// <summary>
        /// Test the property 'ProxyFlow'
        /// </summary>
        [Test]
        public void ProxyFlowTest()
        {
            // TODO unit test for the property 'ProxyFlow'
        }

    }

}
