/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoresBasicReleaseDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoresBasicReleaseDetailsTests
    {
        // TODO uncomment below to declare an instance variable for StoresBasicReleaseDetails
        //private StoresBasicReleaseDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoresBasicReleaseDetails
            //instance = new StoresBasicReleaseDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoresBasicReleaseDetails
        /// </summary>
        [Test]
        public void StoresBasicReleaseDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoresBasicReleaseDetails
            //Assert.IsInstanceOfType<StoresBasicReleaseDetails> (instance, "variable 'instance' is a StoresBasicReleaseDetails");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'ShortVersion'
        /// </summary>
        [Test]
        public void ShortVersionTest()
        {
            // TODO unit test for the property 'ShortVersion'
        }
        /// <summary>
        /// Test the property 'UploadedAt'
        /// </summary>
        [Test]
        public void UploadedAtTest()
        {
            // TODO unit test for the property 'UploadedAt'
        }
        /// <summary>
        /// Test the property 'DestinationType'
        /// </summary>
        [Test]
        public void DestinationTypeTest()
        {
            // TODO unit test for the property 'DestinationType'
        }
        /// <summary>
        /// Test the property 'DistributionStores'
        /// </summary>
        [Test]
        public void DistributionStoresTest()
        {
            // TODO unit test for the property 'DistributionStores'
        }

    }

}
