/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TestRun
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TestRunTests
    {
        // TODO uncomment below to declare an instance variable for TestRun
        //private TestRun instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TestRun
            //instance = new TestRun();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TestRun
        /// </summary>
        [Test]
        public void TestRunInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TestRun
            //Assert.IsInstanceOfType<TestRun> (instance, "variable 'instance' is a TestRun");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Test]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'TestSeries'
        /// </summary>
        [Test]
        public void TestSeriesTest()
        {
            // TODO unit test for the property 'TestSeries'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Test]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'RunStatus'
        /// </summary>
        [Test]
        public void RunStatusTest()
        {
            // TODO unit test for the property 'RunStatus'
        }
        /// <summary>
        /// Test the property 'ResultStatus'
        /// </summary>
        [Test]
        public void ResultStatusTest()
        {
            // TODO unit test for the property 'ResultStatus'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Test]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'TestType'
        /// </summary>
        [Test]
        public void TestTypeTest()
        {
            // TODO unit test for the property 'TestType'
        }

    }

}
