/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V01appsownerNameappNamedistributionStoresIntuneDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V01appsownerNameappNamedistributionStoresIntuneDetailsTests
    {
        // TODO uncomment below to declare an instance variable for V01appsownerNameappNamedistributionStoresIntuneDetails
        //private V01appsownerNameappNamedistributionStoresIntuneDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V01appsownerNameappNamedistributionStoresIntuneDetails
            //instance = new V01appsownerNameappNamedistributionStoresIntuneDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V01appsownerNameappNamedistributionStoresIntuneDetails
        /// </summary>
        [Test]
        public void V01appsownerNameappNamedistributionStoresIntuneDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V01appsownerNameappNamedistributionStoresIntuneDetails
            //Assert.IsInstanceOfType<V01appsownerNameappNamedistributionStoresIntuneDetails> (instance, "variable 'instance' is a V01appsownerNameappNamedistributionStoresIntuneDetails");
        }


        /// <summary>
        /// Test the property 'TargetAudience'
        /// </summary>
        [Test]
        public void TargetAudienceTest()
        {
            // TODO unit test for the property 'TargetAudience'
        }
        /// <summary>
        /// Test the property 'AppCategory'
        /// </summary>
        [Test]
        public void AppCategoryTest()
        {
            // TODO unit test for the property 'AppCategory'
        }

    }

}
