/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJsonTests
    {
        // TODO uncomment below to declare an instance variable for V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson
        //private V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson
            //instance = new V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson
        /// </summary>
        [Test]
        public void V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJsonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson
            //Assert.IsInstanceOfType<V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson> (instance, "variable 'instance' is a V01appsownerNameappNamedistributionStoresIntuneDetails1SecretJson");
        }


        /// <summary>
        /// Test the property 'IdToken'
        /// </summary>
        [Test]
        public void IdTokenTest()
        {
            // TODO unit test for the property 'IdToken'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }
        /// <summary>
        /// Test the property 'RefreshTokenExpiry'
        /// </summary>
        [Test]
        public void RefreshTokenExpiryTest()
        {
            // TODO unit test for the property 'RefreshTokenExpiry'
        }

    }

}
