/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V01appsownerNameappNameanalyticscrashGroupsCrashGroups
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V01appsownerNameappNameanalyticscrashGroupsCrashGroupsTests
    {
        // TODO uncomment below to declare an instance variable for V01appsownerNameappNameanalyticscrashGroupsCrashGroups
        //private V01appsownerNameappNameanalyticscrashGroupsCrashGroups instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V01appsownerNameappNameanalyticscrashGroupsCrashGroups
            //instance = new V01appsownerNameappNameanalyticscrashGroupsCrashGroups();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V01appsownerNameappNameanalyticscrashGroupsCrashGroups
        /// </summary>
        [Test]
        public void V01appsownerNameappNameanalyticscrashGroupsCrashGroupsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V01appsownerNameappNameanalyticscrashGroupsCrashGroups
            //Assert.IsInstanceOfType<V01appsownerNameappNameanalyticscrashGroupsCrashGroups> (instance, "variable 'instance' is a V01appsownerNameappNameanalyticscrashGroupsCrashGroups");
        }


        /// <summary>
        /// Test the property 'CrashGroupId'
        /// </summary>
        [Test]
        public void CrashGroupIdTest()
        {
            // TODO unit test for the property 'CrashGroupId'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Test]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }

    }

}
