/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V2MissingSymbolCrashGroupsInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V2MissingSymbolCrashGroupsInfoResponseTests
    {
        // TODO uncomment below to declare an instance variable for V2MissingSymbolCrashGroupsInfoResponse
        //private V2MissingSymbolCrashGroupsInfoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V2MissingSymbolCrashGroupsInfoResponse
            //instance = new V2MissingSymbolCrashGroupsInfoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V2MissingSymbolCrashGroupsInfoResponse
        /// </summary>
        [Test]
        public void V2MissingSymbolCrashGroupsInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V2MissingSymbolCrashGroupsInfoResponse
            //Assert.IsInstanceOfType<V2MissingSymbolCrashGroupsInfoResponse> (instance, "variable 'instance' is a V2MissingSymbolCrashGroupsInfoResponse");
        }


        /// <summary>
        /// Test the property 'TotalCrashCount'
        /// </summary>
        [Test]
        public void TotalCrashCountTest()
        {
            // TODO unit test for the property 'TotalCrashCount'
        }

    }

}
